package Controllers;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

public class AdminDashboardFXMLController {
	@FXML
	private Button ExitBtn;

	// Event Listener on Button[#ExitBtn].onAction
	@FXML
	public void ExitAct(ActionEvent event) {
		// TODO Autogenerated
		System.exit(0);
	}
}
